name: CI/CD Pipeline
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Model Zoo branch name'
        default: 'develop'
        required: true
        type: string
      mz_version:
        description: 'Model Zoo version'
        default: '2.12.0'
        required: true
        type: string
      aikit_release:
        description: 'Target AIKit version'
        default: '2024.0.0'
        required: true
        type: string
      is_lkg_drop:
        description: 'LKG drop flag'
        default: false
        required: true
        type: boolean
  
jobs:
  scans:
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/Scans.yml@develop
    secrets: inherit
  workload-tests:
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/mz-workload-launcher.yml@develop
    secrets: inherit
    with:
      aikit_release: ${{ inputs.aikit_release || '2024.0.0' }}
      is_lkg_drop: ${{ inputs.is_lkg_drop || true }}
  mz-drop:
    #if: ${{ always() && needs.scan-snyk.result=='success'  && needs.workload-tests.result=='success' }}
    needs: [scans, workload-tests]
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/mz-aikit-drop.yml@develop   
    with:
      target_branch: ${{ inputs.target_branch || 'develop' }}
      mz_version: ${{ inputs.mz_version || '2.12.0' }}
      aikit_release: ${{ inputs.aikit_release || '2024.0.0' }}
      is_lkg_drop: ${{ inputs.is_lkg_drop || true }}
    secrets: inherit
