name: CI/CD Pipeline
on: 
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Model Zoo branch name'
        default: develop
        required: true
        type: string
      mz_version:
        description: 'Model Zoo version'
        default: '2.11.0'
        required: true
        type: string
      aikit_release:
        description: 'Target AIKit version'
        default: '2023.2.0'
        required: true
        type: string
      is_lkg_drop:
        description: 'LKG drop flag'
        default: true
        required: true
        type: boolean
  
  #run job daily on week days at 22:00 PDT
  schedule:
    - cron:  '00 22 * * MON-FRI'
  
  repository_dispatch:
    
jobs:
  scans:
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/Scans.yml@develop
    secrets: inherit
  #TODO: Enable below three lines when workloads test workflow is merged to develop branch
  #test-workloads:
    #uses: intel-sandbox/frameworks.ai.models.intel-models/.github/workflows/test-workloads.yml@develop
    #secrets: inherit
  mz-drop:
    needs: [scans] #TODO: add test-workloads job to the array when is merged to deveop branch
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/mz-aikit-drop.yml@develop
    with:
      target_branch: ${{ inputs.target_branch }}
      mz_version: ${{ inputs.mz_version }}
      aikit_release: ${{ inputs.aikit_release }}
      is_lkg_drop: ${{ inputs.is_lkg_drop }}
    secrets: inherit
