name: CI/CD Pipeline
on: 
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Model Zoo branch name'
        default: develop
        required: true
        type: string
      mz_version:
        description: 'Model Zoo version'
        default: '2.11.0'
        required: true
        type: string
      aikit_release:
        description: 'Target AIKit version'
        default: '2023.2.0'
        required: true
        type: string
      is_lkg_drop:
        description: 'LKG drop flag'
        default: false
        required: true
        type: boolean
  
  #run job daily on week days at 22:00 PDT
  schedule:
    - cron:  '00 22 * * MON-FRI'
  
  repository_dispatch:
    
jobs:
  scan-snyk:
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/Scanner_Snyk.yml@develop
    with:
      repos: frameworks.ai.models.intel-models
      ref: ${{ github.head_ref }}
      scan_type: monitor
      snyk_org: iags_mlp
    secrets:
      SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
  scan-bandit:
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/Scanner_Bandit.yml@develop
    with:
      repos: frameworks.ai.models.intel-models
      refs: ${{ github.head_ref }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  scan-coverity:
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/Scanner_Coverity.yml@develop
    with:
      repos: frameworks.ai.models.intel-models
      refs: ${{ github.head_ref }}
      projectType: python
      url: https://coverityent.devtools.intel.com/prod8
      stream: model_zoo_first_test
    secrets:
      USER: tf_qa_prod
      PASSWORD: ${{ secrets.TF_QA_PROD }}
      token: ${{ secrets.GITHUB_TOKEN }}
  scan-checkmarx:
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/Scanner_Checkmarx.yml@develop
    with:
      repos: frameworks.ai.models.intel-models
      refs: ${{ github.head_ref }}
      projectid: 352866
      region: INTEL-AMR
      checkmarx_timeout: 5400
      checkmarx_ignore_vulnerabilities: true
    secrets:
      SYS_ACCOUNT: tf_qa_prod
      CHECKMARX_PASSWORD: ${{ secrets.TF_QA_PROD }}
      token: ${{ secrets.GITHUB_TOKEN }}
  #TODO: Enable below three lines when workloads test workflow is merged to develop branch
  #test-workloads:
    #uses: intel-sandbox/frameworks.ai.models.intel-models/.github/workflows/test-workloads.yml@develop
    #secrets: inherit
  mz-drop:
    if: ${{ always() && needs.scan-snyk.result=='success' }}
    needs: [scan-snyk, scan-bandit, scan-coverity, scan-checkmarx] #TODO: add test-workloads job to the array when is merged to deveop branch
    uses: intel-innersource/frameworks.ai.models.intel-models/.github/workflows/mz-aikit-drop-dummy.yml@develop
    with:
      target_branch: ${{ inputs.target_branch || 'develop' }}
      mz_version: ${{ inputs.mz_version || '2.11.0' }}
      aikit_release: ${{ inputs.aikit_release || '2023.2.0' }}
      is_lkg_drop: ${{ inputs.is_lkg_drop || true }}
    secrets: inherit
