name: Model zoo drop for AIKit

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Model zoo branch name'
        default: develop
        required: true
        type: string
      mz_version:
        description: 'Model zoo version'
        default: '2.11.0'
        required: true
        type: string
      aikit_release:
        description: 'Target AIKit version'
        default: '2023.2.0'
        required: true
        type: string
  workflow_call:
    inputs:
      target_branch:
        description: 'Model zoo branch name'
        required: true
        type: string
      mz_version:
        description: 'Model zoo version'
        required: true
        type: string
      aikit_release:
        description: 'Target AIKit version'
        required: true
        type: string
      is_lkg_drop:
        description: 'LKG drop indicator flag'
        required: true
        type: boolean

jobs:
  aikit_drop:
    runs-on: [ gasp ]
    container:
      image: python:3.9
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      options: --privileged
    continue-on-error: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: intel-innersource/frameworks.ai.models.intel-models
          token: ${{ secrets.GITHUB_TOKEN }}
          path: modelzoo
          ref: ${{inputs.target_branch}}

      - name: Create model zoo bits
        run: |
          cd ${GITHUB_WORKSPACE}/modelzoo/.github/utils/aikit
          ./create_mz_bits.sh ${{ inputs.mz_version }} ${{ inputs.aikit_release }} ${GITHUB_WORKSPACE}
      - name: Make a drop to artifacory
        run: |
          echo "Not dropping to artifactory for now.."
          echo "Getting a token to access intel-innersource/frameworks.devops.oneapi.tools.component-drop-tool repo"
          #cd ${GITHUB_WORKSPACE}
          #git clone https://tf_qa_prod:${{ secrets.TF_QA_PROD }}@github.com/intel-innersource/frameworks.devops.oneapi.tools.component-drop-tool.git oneapi_drop_tool
          #cd oneapi_drop_tool
          #git submodule update --init --remote --recursive
          #python -m pip install -r requirements.txt
          #python cdt.py --user=tf_qa_prod --password=${{ secrets.TF_QA_PROD }} drop -p MZ -r ${{inputs.aikit_release}} -c l_drop -cd ${GITHUB_WORKSPACE}/l_model-zoo-${{ inputs.mz_version }}-${{ inputs.aikit_release }}-drop/ -b ${GITHUB_WORKSPACE}/l_model-zoo-${{ inputs.mz_version }}-${{ inputs.aikit_release }}-drop/boms/l_modelzoo.txt

