name: Model zoo drop for AIKit

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Model zoo branch name'
        default: develop
        required: true
        type: string
      mz_version:
        description: 'Model zoo version'
        default: '2.11.0'
        required: true
        type: string
      aikit_release:
        description: 'Target AIKit version'
        default: '2023.2.0'
        required: true
        type: string
jobs:
  aikit_drop:
    runs-on: [ gasp ]
    container:
      image: python:3.9
      env:
        http_proxy: ${{ secrets.HTTP_PROXY }}
        https_proxy: ${{ secrets.HTTPS_PROXY }}
        no_proxy: ${{ secrets.NO_PROXY }}
      options: --privileged
    continue-on-error: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: intel-innersource/frameworks.ai.models.intel-models
          token: ${{ secrets.GITHUB_TOKEN }}
          path: modelzoo
          ref: ${{inputs.target_branch}}
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: intel-innersource/frameworks.devops.oneapi.tools.component-drop-tool
          token: ${{ secrets.GITHUB_TOKEN }}
          path: oneapi_drop_tool
          submodules: true

      - name: Execute Bash Commands
        run: |
          # create model zoo bits

          cd ${GITHUB_WORKSPACE}/modelzoo/.github/utils/aikit
          ./create_mz_bits.sh ${{ inputs.mz_version }} ${{ inputs.aikit_release }} ${GITHUB_WORKSPACE} ${{ inputs.target_branch }}
          # make a drop to artifacory
          cd ${GITHUB_WORKSPACE}/oneapi_drop_tool
          python -m pip install -r requirements.txt
          # python cdt.py --user=tf_qa_prod --password=${{ secrets.TF_QA_PROD }} drop -p MZ -r ${{inputs.aikit_release}} -c l_drop -cd ${GITHUB_WORKSPACE}/l_model-zoo-${{ inputs.mz_version }}-${{ inputs.aikit_release }}-drop/ -b ${GITHUB_WORKSPACE}/l_model-zoo-${{ inputs.mz_version }}-${{ inputs.aikit_release }}-drop/boms/l_modelzoo.txt

