name: Scans
on:
  pull_request:
    branches: [develop]
  workflow_call:

jobs:
  scan-snyk:
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Snyk_Project_Repo.yml@one-ci-cd
    with:
      repos: frameworks.ai.models.intel-models
      refs: ${{ github.head_ref }}
      scan_type: monitor
      snyk_org: iags_mlp
      runners: 'k8-runners'
    secrets:
      SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
  scan-coverity:
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Coverity.yml@one-ci-cd
    with:
      repos: frameworks.ai.models.intel-models
      refs: ${{ github.head_ref }}
      projectType: python
      url: https://coverityent.devtools.intel.com/prod8
      stream: model_zoo_first_test
      runners: 'k8-runners'
    secrets:
      USER: tf_qa_prod
      PASSWORD: ${{ secrets.TF_QA_PROD }}
      token: ${{ secrets.GITHUB_TOKEN }}
