name: Scanner-Coverity
on:
  workflow_dispatch:
    inputs:
      repos:
        description: 'Enter Project repo for which you want to run coverity scan:'
        required: true
        type: string
        default: frameworks.ai.models.intel-models
      refs:
        description: 'Enter Project branch, tag:'
        required: true
        type: string
        default: develop
      buildCommand:
        description: 'Enter Project build command or Script:'
        required: false
        type: string
      projectType:
        description: 'Enter project type: (gcc, java or python)'
        required: true
        type: string
        default: python
      url:
        description: 'Enter coverity server url:'
        required: true 
        type: string
      stream:
        description: 'Enter coverity stream name:'
        required: true
        type: string
      runner_label:
        description: 'Enter one label of the runner that will execute the workflow:'
        required: true
        type: string
        default: k8-runners

jobs:
  scan-coverity:
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Coverity.yml@one-ci-cd
    with:
      repos: ${{ inputs.repos }}
      refs: ${{ inputs.refs }}
      projectType: ${{ inputs.projectType }}
      url: ${{ inputs.url }}
      stream: ${{ inputs.stream }}
      runner_label: ${{ inputs.runner_label }}
    secrets:
      USER: tf_qa_prod
      PASSWORD: ${{ secrets.TF_QA_PROD }}
      token: ${{ secrets.GITHUB_TOKEN }}
